GTCEuStartupEvents.registry('gtceu:material', event => {

    event.create('alumina')
        .dust()
        .ore()
        .color(0x09474a).iconSet(GTMaterialIconSet.DULL)
        .element(GTElements.get('alumina'))
    event.create('chromium_iii_oxide')
        .dust()
        .color(0x3dc34d).iconSet(GTMaterialIconSet.DULL)
        .element(GTElements.get('chromium_iii_oxide'))
    event.create('sodium_carbonate_solution')
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .color(0x636389)
    event.create('sodium_chromate_solution')
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .color(0xbbb310)
    event.create('sodium_dichromate_solution')
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .color(0xb55a10)
    event.create('sodium_sulfate')
        .dust()
        .color(0xc6c6c6)
        .components('2x sodium', '1x sulfur', '4x oxygen')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('calcium_sulfide')
        .dust()
        .color(0xd8e09b)
        .components('1x calcium', '1x sulfur')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('ambroterra_hydroxide')
        .dust()
        .color(0x879e20)
        .components('1x ambrosium', '1x terra')
    event.create('manacrystalline_slurry')
        .liquid()
        .color(0x2078e3)
    event.create('raw_terrasteel')
        .liquid()
        .color(0x198204)
    event.create('unstable_terrasteel')
        .liquid()
        .color(0x12a146)
    event.create('refined_mana')
        .liquid()
        .color(0x3caef0)

})

GTCEuStartupEvents.materialModification(event => {
    GTMaterials.get('sodium_hypophosphite').setFormula('NaPO₂H₂', true)
})
