ServerEvents.recipes(event => {

    event.recipes.gtceu.large_chemical_reactor('alfheim_mix')
        .itemInputs('2x gtceu:terrasteel_dust')
        .inputFluids('gtceu:sulfuric_acid 1000')
        .inputFluids('gtceu:refined_mana 500')
        .itemOutputs('2x gtceu:manasteel_dust')
        .outputFluids('gtceu:alfheim_mixture 1000')
        .duration(200)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.mixer('rare_alfheim_metal_mix')
        .itemInputs('1x gtceu:netherite_dust', '2x gtceu:elementium_dust')
        .inputFluids('gtceu:alfheim_mixture 1000')
        .inputFluids('gtceu:hydrogen 500')
        .itemOutputs('7x gtceu:rare_alfheim_metal_mixture_dust')
        .duration(100)
        .EUt(GTValues.VA[GTValues.IV])
    event.recipes.gtceu.centrifuge('unrefined_alfsteel_dust')
        .itemInputs('7x gtceu:rare_alfheim_metal_mixture_dust')
        .itemOutputs('4x gtceu:unrefined_alfsteel_dust', '2x gtceu:sodium_hydroxide_dust')
        .outputFluids('gtceu:diluted_sulfuric_acid 1000')
        .duration(200)
        .EUt(GTValues.VA[GTValues.LuV])
    event.recipes.gtceu.electric_blast_furnace('aflsteel_ebf')
        .itemInputs('4x gtceu:unrefined_alfsteel_dust', '1x gtceu:tungsten_dust')
        .inputFluids('blasmatech:mana 1000')
        .itemOutputs('3x mythicbotany:alfsteel_ingot')
        .duration(800)
        .blastFurnaceTemp(4500)
        .EUt(GTValues.VA[GTValues.ZPM])
})