ServerEvents.recipes(event => {
  //Sodium hydroxide
    event.recipes.gtceu.mixer('sodium_hydroxide_mix')
        .itemInputs('1x gtceu:sodium_hydroxide_dust')
        .inputFluids('minecraft:water 1000')
        .outputFluids('gtceu:sodium_hydroxide_solution 1000')
        .duration(30)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.mixer('bauxite_slurry_from_small_bauxite')
        .itemInputs('29x gtceu:small_bauxite_dust')
        .inputFluids('gtceu:sodium_hydroxide_solution 6000')
        .outputFluids('gtceu:bauxite_slurry 6000')
        .duration(60)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.mixer('bauxite_slurry_from_bauxite')
        .itemInputs('29x gtceu:bauxite_dust')
        .inputFluids('gtceu:sodium_hydroxide_solution 2400')
        .outputFluids('gtceu:bauxite_slurry 24000')
        .duration(15)
        .EUt(GTValues.VA[GTValues.IV])
    event.recipes.gtceu.fluid_heater('heated_bauxite')
        .inputFluids('gtceu:bauxite_slurry 4000')
        .outputFluids('gtceu:heated_bauxite_slurry 4000')
        .duration(80)
        .EUt(GTValues.VA[GTValues.LV])
    event.recipes.gtceu.centrifuge('red_mud_spin')
        .inputFluids('gtceu:heated_bauxite_slurry 12000')
        .outputFluids('gtceu:red_mud 3000')
        .outputFluids('gtceu:sodium_aluminate_solution 9000')
        .duration(30)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.dehydration_chamber('sodium_aluminate_dehydration')
        .inputFluids('gtceu:sodium_aluminate_solution 9000')
        .itemOutputs('27x gtceu:sodium_aluminate_dust', '5x gtceu:sodium_silicate_dust')
        .chancedOutput(Item.of('gtceu:gallium_dust', 1), 1000, 500)
        .duration(100)
        .EUt(GTValues.VA[GTValues.HV])
    event.recipes.gtceu.chemical_reactor('aluminium_hydroxide_from_cr')
        .itemInputs('9x gtceu:sodium_aluminate_dust')
        .inputFluids('gtceu:carbon_dioxide 1000')
        .inputFluids('minecraft:water 3000')
        .itemOutputs('14x gtceu:aluminium_hydroxide_dust', '6x gtceu:soda_ash_dust')
        .duration(90)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.chemical_reactor('good_alum_hydrox')
        .itemInputs('4x gtceu:sodium_aluminate_dust')
        .inputFluids('minecraft:water 2000')
        .notConsumable('1x gtceu:aluminium_hydroxide_dust')
        .itemOutputs('7x gtceu:aluminium_hydroxide_dust', '3x gtceu:sodium_hydroxide_dust')
        .duration(150)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.electric_blast_furnace('alumina_ebf')
        .itemInputs('14x gtceu:aluminium_hydroxide_dust')
        .itemOutputs('5x gtceu:alumina_dust')
        .outputFluids('minecraft:water 3000')
        .blastFurnaceTemp(1100)
        .duration(180)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.chemical_reactor('sodium_hydroxide_from_dust')
        .itemInputs('6x gtceu:sodium_silicate_dust')
        .inputFluids('gtceu:hydrogen 2000')
        .itemOutputs('6x gtceu:sodium_hydroxide_dust', '3x gtceu:silicon_dioxide_dust')
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.mixer('neutral_red_mud_mix')
        .inputFluids('gtceu:red_mud 2000')
        .inputFluids('gtceu:hydrochloric_acid 3000')
        .outputFluids('gtceu:neutralised_red_mud 3000')
        .duration(120)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.centrifuge('red_mud_slurry_from_neutral')
        .inputFluids('gtceu:neutralised_red_mud 3000')
        .outputFluids('gtceu:red_mud_slurry 2000')
        .outputFluids('gtceu:diluted_hydrochloric_acid 2000')
        .outputFluids('gtceu:salt_water 4000')
        .duration(100)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.centrifuge('red_mud_slury_decomp')
        .inputFluids('gtceu:red_mud_slurry 1000')
        .chancedOutput('3x gtceu:rutile_dust', 8500, 300)
        .chancedOutput('2x gtceu:vanadium_dust', 500, 400)
        .chancedOutput('5x gtceu:hematite_dust', 3000, 500)
        .chancedOutput('2x gtceu:quicklime_dust', 700, 250)
        .chancedOutput('5x gtceu:alumina_dust', 1500, 400)
        .outputFluids('minecraft:water 2000')
        .duration(640)
        .EUt(GTValues.VA[GTValues.MV])

})