ServerEvents.recipes(event => {

    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_chromite' })
    event.remove({ id: 'gtceu:centrifuge/ruby_slurry_centrifuging' })
    event.remove({ id: 'gtceu:electrolyzer/decomposition_electrolyzing_ruby' })

    event.recipes.gtceu.electric_blast_furnace('aluminium_from_alumina_ebf')
        .itemInputs('10x gtceu:alumina_dust', '3x gtceu:carbon_dust')
        .itemOutputs('4x gtceu:aluminium_ingot')
        .outputFluids('gtceu:carbon_dioxide 3000')
        .blastFurnaceTemp(1200)
        .duration(1200)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.mixer('sodium_carbonate_mix')
        .itemInputs('6x gtceu:soda_ash_dust')
        .inputFluids('minecraft:water 1000')
        .outputFluids('gtceu:sodium_carbonate_solution 1000')
        .duration(60)
        .EUt(GTValues.VA[GTValues.LV])
    //Step 1
    event.recipes.gtceu.chemical_reactor('sodium_chromate_sol')
        .itemInputs('7x gtceu:chromite_dust')
        .inputFluids('gtceu:oxygen 7000')
        .inputFluids('gtceu:sodium_carbonate_solution 4000')
        .itemOutputs('5x gtceu:iron_dust')
        .outputFluids('gtceu:carbon_dioxide 4000')
        .outputFluids('gtceu:sodium_chromate_solution 4000')
        .duration(120)
        .EUt(GTValues.VA[GTValues.MV])
    //Step 2
    event.recipes.gtceu.dehydration_chamber('sodium_chromate_dehydration')
        .inputFluids('gtceu:sulfuric_acid 1000')
        .inputFluids('gtceu:sodium_chromate_solution 2000')
        .itemOutputs('7x gtceu:sodium_sulfate_dust')
        .outputFluids('gtceu:sodium_dichromate_solution 1000')
        .duration(180)
        .EUt(GTValues.VA[GTValues.MV])
    //Step 3
    event.recipes.gtceu.dehydration_chamber('chromium_3_oxide_from_dichromate')
        .itemInputs('2x gtceu:carbon_dust')
        .inputFluids('gtceu:sodium_dichromate_solution 1000')
        .itemOutputs('6x gtceu:soda_ash_dust', '5x gtceu:chromium_iii_oxide_dust')
        .outputFluids('gtceu:carbon_monoxide 1000')
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])
    //Step 4
    event.recipes.gtceu.electric_blast_furnace('chrome_dust')
        .itemInputs('5x gtceu:chromium_iii_oxide_dust', '2x gtceu:aluminium_dust')
        .itemOutputs('2x gtceu:chromium_dust', '5x gtceu:alumina_dust')
        .blastFurnaceTemp(1200)
        .duration(200)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.chemical_reactor('gtceu:chemical_reactor/soda_ash_from_sodium_sulfate')
        .itemInputs('7x gtceu:sodium_sulfate_dust')
        .inputFluids('gtceu:carbon_monoxide 1000')
        .itemOutputs('6x gtceu:soda_ash_dust')
        .outputFluids('gtceu:sulfur_dioxide 1000')
        .duration(40)
        .EUt(GTValues.VA[GTValues.MV]);

})