ServerEvents.recipes(event => {
    event.recipes.gtceu.macerator('ancient_debris_dust_mace')
        .itemInputs('1x minecraft:ancient_debris')
        .itemOutputs('3x gtceu:ancient_debris_dust')
        .duration(80)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.mixer('anc_debris_mixture')
        .itemInputs('7x gtceu:ancient_debris_dust')
        .inputFluids('gtceu:liquid_nether_air 1000')
        .outputFluids('gtceu:ancient_debris_mixture 7000')
        .duration(120)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.chemical_bath('netherite_slurry')
        .itemInputs('2x occultism:iesnium_dust')
        .inputFluids('gtceu:ancient_debris_mixture 1000')
        .outputFluids('gtceu:netherite_slurry 2000')
        .duration(160)
        .EUt(GTValues.VA[GTValues.HV])
    event.recipes.gtceu.centrifuge('netherite_slurry_spinny')
        .inputFluids('gtceu:netherite_slurry 2000')
        .itemOutputs('2x minecraft:netherite_scrap', '3x gtceu:obsidian_dust', '1x minecraft:glowstone_dust', '2x gtceu:activated_iesnium_dust')
        .chancedOutput('occultism:iesnium_dust', 700, 250)
        .duration(240)
        .EUt(GTValues.VA[GTValues.HV])
    //Ingot
    event.recipes.gtceu.electric_blast_furnace('impure_netherite_ebf')
        .itemInputs('1x minecraft:netherite_scrap', '1x gtceu:manasteel_dust')
        .inputFluids('gtceu:nether_air 150')
        .itemOutputs('1x gtceu:impure_netherite_ingot')
        .blastFurnaceTemp(3000)
        .duration(600)
        .EUt(GTValues.VA[GTValues.HV])
    event.recipes.gtceu.electric_blast_furnace('netherite_ingot_ebf')
        .itemInputs('1x gtceu:impure_netherite_ingot')
        .inputFluids('gtceu:rose_gold 144')
        .itemOutputs('1x minecraft:netherite_ingot')
        .blastFurnaceTemp(3400)
        .duration(800)
        .EUt(GTValues.VA[GTValues.EV])
})