ServerEvents.recipes(event => {
    event.recipes.gtceu.chemical_reactor('gtceu:chemreactor/ambroterra_hydroxide')
        .itemInputs(['4x gtceu:terra_dust', '4x gtceu:ambrosium_dust'])
        .inputFluids('gtceu:steel 576')
        .itemOutputs('12x gtceu:ambroterra_hydroxide_dust')
        .duration(400)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.mixer('gtceu:mixer/manacrystalline_slurry')
        .itemInputs('botania:mana_diamond')
        .inputFluids('gtceu:hydrochloric_acid 2000')
        .inputFluids('minecraft:water 1000')
        .outputFluids('gtceu:manacrystalline_slurry 3000')
        .duration(120)
        .EUt(GTValues.VA[GTValues.MV]);
    event.recipes.gtceu.dehydration_chamber('gtceu:dehydration_chamber/raw_terrasteel')
        .itemInputs('botania:mana_pearl')
        .inputFluids('gtceu:manacrystalline_slurry 1000')
        .inputFluids('gtceu:sulfuric_acid 1000')
        .outputFluids('gtceu:raw_terrasteel 1000')
        .outputFluids('gtceu:diluted_sulfuric_acid 1000')
        .duration(220)
        .EUt(GTValues.VA[GTValues.MV]);
    event.recipes.gtceu.chemical_reactor('gtceu:chemical_reactor/unstable_terrasteel')
        .inputFluids(['gtceu:raw_terrasteel 1000', 'gtceu:refined_mana 1000'])
        .notConsumable('48x gtceu:ambroterra_hydroxide_dust')
        .outputFluids('gtceu:unstable_terrasteel 2000')
        .duration(120)
        .EUt(GTValues.VA[GTValues.MV]);
    event.recipes.gtceu.dehydration_chamber('gtceu:dehydration_chamber/terrasteel_dust')
        .itemInputs(['gtceu:manasteel_dust', 'botania:mana_powder'])
        .inputFluids('gtceu:unstable_terrasteel 1000')
        .itemOutputs('2x gtceu:terrasteel_dust')
        .outputFluids('gtceu:chlorine 500')
        .duration(300)
        .EUt(GTValues.VA[GTValues.MV])
})