ServerEvents.recipes(event => {
    event.recipes.gtceu.autoclave('sodium_tungstate')
        .itemInputs('7x gtceu:tungstate_dust', '2x gtceu:sodium_dust')
        .inputFluids('minecraft:water 4000')
        .itemOutputs('2x gtceu:lithium_dust')
        .outputFluids('gtceu:sodium_tungstate 1000')
        .duration(140)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.large_chemical_reactor('sodium_tungstate_lcr')
        .itemInputs('3x gtceu:calcium_chloride_dust')
        .inputFluids('gtceu:sodium_tungstate 1000')
        .itemOutputs('6x gtceu:scheelite_dust', '4x gtceu:salt_dust')
        .outputFluids('gtceu:hydrochloric_acid 2000')
        .duration(180)
        .EUt(GTValues.VA[GTValues.HV])
    event.recipes.gtceu.large_chemical_reactor('tungstic_acid_lcr')
        .itemInputs('6x gtceu:scheelite_dust')
        .inputFluids('gtceu:hydrochloric_acid 2000')
        .itemOutputs('3x gtceu:calcium_chloride_dust', '7x gtceu:tungstic_acid_dust')
        .duration(120)
        .EUt(GTValues.VA[GTValues.EV])
    event.recipes.gtceu.dehydration_chamber('tungstic_acid_dehydration')
        .itemInputs('7x gtceu:tungstic_acid_dust')
        .itemOutputs('4x gtceu:tungsten_oxide_dust')
        .duration(80)
        .EUt(GTValues.VA[GTValues.MV])
    event.recipes.gtceu.electric_blast_furnace('tungsten_from_tungsten_oxide')
        .itemInputs('4x gtceu:tungsten_oxide_dust')
        .inputFluids('gtceu:hydrogen 250')
        .itemOutputs('2x gtceu:tungsten_dust')
        .outputFluids('gtceu:steam 500')
        .blastFurnaceTemp(3700)
        .duration(300)
        .EUt(GTValues.VA[GTValues.HV])    
    
})