WorldgenEvents.remove(event => {
  event.removeOres(props => {
    props.blocks = [
      'occultism:silver_ore_deepslate',
      'occultism:silver_ore',
      "ad_astra:mars_diamond_ore",
      "ad_astra:mars_ice_shard_ore",
      "ad_astra:mars_iron_ore",
      "ad_astra:mars_ostrum_ore",
      'ad_astra:venus_coal_ore',
      'ad_astra:venus_gold_ore',
      'ad_astra:venus_diamond_ore',
      'ad_astra:venus_calorite_ore',
      'malum:deepslate_soulstone_ore',
      'malum:soulstone_ore',
      'malum:blazing_quartz_ore',
      'malum:deepslate_quartz_ore',
      'malum:natural_quartz_ore',
      'malum:cthonic_gold_ore',
      'malum:brilliant_stone',
      'malum:brilliant_deepslate',
      'gtceu:nickel_vein_ow',
      'gtceu:galena_vein_ow',
      'forestry:tin_ore',
      'forestry:deepslate_tin_ore',
      'forestry:apatite_ore',
      'forestry:deepslate_apatite_ore'
    ]
  })



  event.removeFeatureById('raw_generation', [
    //FOR SOME REASON ADASTRA GENERATES ORES AT THIS GENERATION STEP      
    'ad_astra:moon_iron_ore',
    'ad_astra:deepslate_desh_ore',
    'ad_astra:moon_desh_ore',
    'ad_astra:moon_cheese_ore',
    'ad_astra:moon_ice_shard_ore',
    "ad_astra:mars_diamond_ore",
    "ad_astra:mars_ice_shard_ore",
    "ad_astra:mars_iron_ore",
    "ad_astra:mars_ostrum_ore",
    'ad_astra:venus_coal_ore',
    'ad_astra:venus_gold_ore',
    'ad_astra:venus_diamond_ore',
    'ad_astra:venus_calorite_ore',
    'malum:deepslate_soulstone_ore',
    'malum:soulstone_ore',
    'malum:blazing_quartz_ore',
    'malum:deepslate_quartz_ore',
    'malum:natural_quartz_ore',
    'malum:cthonic_gold_ore',
    'malum:brilliant_stone',
    'malum:brilliant_deepslate',
    'gtceu:nickel_vein_ow',
    'gtceu:galena_vein_ow',
    'forestry:tin_ore',
    'forestry:deepslate_tin_ore',
    'forestry:apatite_ore',
    'forestry:deepslate_apatite_ore'
  ])
  event.removeFeatureById('underground_ores', [
    //FOR SOME REASON ADASTRA GENERATES ORES AT THIS GENERATION STEP      
    'aether:gravitite_ore',
    'aether:gravitite_ore_buried',
    'aether:ambrosium_ore',
    'aether:zanite_ore',
    'ad_astra:moon_iron_ore',
    'ad_astra:deepslate_desh_ore',
    'ad_astra:moon_desh_ore',
    'ad_astra:moon_cheese_ore',
    'ad_astra:moon_ice_shard_ore',
    "ad_astra:mars_diamond_ore",
    "ad_astra:mars_ice_shard_ore",
    "ad_astra:mars_iron_ore",
    "ad_astra:mars_ostrum_ore",
    'ad_astra:venus_coal_ore',
    'ad_astra:venus_gold_ore',
    'ad_astra:venus_diamond_ore',
    'ad_astra:venus_calorite_ore',
    'malum:deepslate_soulstone_ore',
    'malum:soulstone_ore',
    'malum:blazing_quartz_ore',
    'malum:deepslate_quartz_ore',
    'malum:natural_quartz_ore',
    'malum:cthonic_gold_ore',
    'malum:brilliant_stone',
    'malum:brilliant_deepslate',
    'gtceu:nickel_vein_ow',
    'gtceu:galena_vein_ow',
    'forestry:tin_ore',
    'forestry:deepslate_tin_ore',
    'forestry:apatite_ore',
    'forestry:deepslate_apatite_ore'
  ])
})
